[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31"
egui_extras = { version = "0.31", features = ["default", "all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }